export interface Task {
  id?: number;             // Auto-generated by the database
  title: string;           // Required when creating a task
  description?: string;    // Optional in DB but usually included
  status?: string;         // Could be "Pending", "Completed", etc.
  dueDate?: string;        // ISO date string from backend
  createdAt?: string;      // ISO datetime string
  updatedAt?: string;      // ISO datetime string
  userId?: number;         // Not always needed on the frontend
}

export interface TaskUpdate {
  title?: string;
  description?: string;
  status?: string;
  dueDate?: string;
}
